name: CI

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'docs/**'
      - '*.md'

env:
  MIX_ENV: test

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14', '1.15', '1.16', '1.17']
        otp: ['25', '26', '27']
        exclude:
          # OTP 27 requires Elixir 1.17+
          - elixir: '1.14'
            otp: '27'
          - elixir: '1.15'
            otp: '27'
          - elixir: '1.16'
            otp: '27'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

  format:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17'
          otp-version: '27'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-27-1.17-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-27-1.17-

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.17', '1.18']
        otp: ['26', '27']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests with coverage
        run: mix coveralls.json

      - name: Upload coverage to Codecov
        if: matrix.elixir == '1.17' && matrix.otp == '27'
        uses: codecov/codecov-action@v3
        with:
          files: ./cover/excoveralls.json
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  credo:
    name: Static Analysis (Credo)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17'
          otp-version: '27'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-27-1.17-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-27-1.17-

      - name: Install dependencies
        run: mix deps.get

      - name: Run Credo
        run: mix credo --strict

  dialyzer:
    name: Static Type Analysis (Dialyzer)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17'
          otp-version: '27'

      - name: Cache dependencies and PLTs
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            priv/plts
          key: deps-plt-${{ runner.os }}-27-1.17-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-plt-${{ runner.os }}-27-1.17-

      - name: Install dependencies
        run: mix deps.get

      - name: Run Dialyzer
        run: mix dialyzer

  quality:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [compile, format, test, credo, dialyzer]
    steps:
      - name: All checks passed
        run: echo "All quality checks have passed successfully!"
